// <auto-generated />
using FrenchShopsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrenchShopsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210213134838_addT_ShopDatabase")]
    partial class addT_ShopDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FrenchShopsApp.Models.T_Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdressShop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomShop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlShop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
